title: Liyan Tang
logo: /assets/img/logo.png
email: lytang@google.com
blank_title: true
favicon: true
description: "Research Scientist at Google Research"
show_downloads: false
google_analytics: UA-202974782-1
remote_theme: BDHU/minimalist@f19d6a6ef015ba93c5aee9ce80339e4959b0ffa7
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
